// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/BuilderV4.tsx": () => import("../components/mockups/BuilderV4.tsx"),
  "./components/mockups/DashboardV3.tsx": () => import("../components/mockups/DashboardV3.tsx"),
  "./components/mockups/RedesignV3.tsx": () => import("../components/mockups/RedesignV3.tsx")
};
